import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        mep: {
          azul: "#2E3552",
          azul2: "#1F3F78",
          azulClaro: "#EEF3FA",
          dorado: "#D4AF5A",
          dorado2: "#B9923F",
          blanco: "#FFFFFF",
          verde: "#2E7D57",
          verdeClaro: "#EEF8F2",
          rojo: "#A9473D",
          rojoClaro: "#FCEFED",
          amarillo: "#A97C2A",
          amarilloClaro: "#FFF8E7",
          gris: "#667085",
          grisClaro: "#F5F7FA",
          borde: "#D9DFE8",
          texto: "#20283B",
          blue: "#2E3552",
          darkBlue: "#1F3F78",
          lightBlue: "#EEF3FA",
          accent: "#1F3F78",
          gold: "#D4AF5A",
          emerald: "#2E7D57",
          coral: "#A9473D",
          amber: "#A97C2A",
          lightBg: "#F5F7FA",
        },
        docente: {
          teal: "#1b5e59",
          darkTeal: "#004641",
          lightTeal: "#d1ebe7",
          tealBorder: "#9fd1c9",
          tealCardBg: "#d7efea",
          amberPrimary: "#e07a2c",
          amberPrimaryHover: "#c8661d",
          amberCardBg: "#fff3eb",
          amberBorder: "#fbd0b6",
          grayBg: "#eef2f6",
          canvas: "#f8f9ff",
          textDark: "#0d1c2e",
          textMuted: "#475569",
        },
        pastel: {
          canvas: "#FAF8F5",
          canvasAlt: "#F5EFEB",
          card: "#FFFFFF",
          sageBg: "#EBF3EE",
          sageBorder: "#C7DEC9",
          sageText: "#1B432D",
          sageAccent: "#2E6847",
          skyBg: "#EBF3FA",
          skyBorder: "#C9DFEE",
          skyText: "#19385C",
          skyAccent: "#2B5C8F",
          lavenderBg: "#F2EEF8",
          lavenderBorder: "#D8CEEA",
          lavenderText: "#37284F",
          lavenderAccent: "#574476",
          sandBg: "#FAF3EB",
          sandBorder: "#EAD7C4",
          sandText: "#573415",
          sandAccent: "#875529",
          coralBg: "#FDF0F0",
          coralBorder: "#F5C6C6",
          coralText: "#6E1C1C",
          coralAccent: "#9E3333",
        },
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "Menlo", "Courier New", "monospace"],
      },
      boxShadow: {
        mepCard: "0 2px 12px -2px rgba(46, 56, 77, 0.06), 0 1px 4px -1px rgba(46, 56, 77, 0.04)",
        mepElevated: "0 8px 24px -4px rgba(46, 56, 77, 0.08), 0 3px 8px -2px rgba(46, 56, 77, 0.04)",
        softPastel: "0 4px 20px -2px rgba(120, 110, 100, 0.07), 0 1px 3px 0 rgba(120, 110, 100, 0.04)",
        cardLg: "0px 2px 8px rgba(15, 23, 42, 0.04), 0px 1px 2px rgba(15, 23, 42, 0.02)",
      },
    },
  },
  plugins: [],
};

export default config;
