// ============================================================================
// CATÁLOGO DE PRODUCCIONES Y ESPACIO COMÚN DE WEBAPPS (III CICLO SECUNDARIA)
// Repositorio de creaciones docentes con soporte para Remix y Adaptación al Aula
// ============================================================================

import { generarCodigoHTMLAutonomo, OpcionesGeneracionWebApp } from "./generadorWebAppEngine";

export interface WebAppComunidad {
  id: string;
  titulo: string;
  autorNombre: string;
  autorRol: string;
  autorDRE: string;
  autorCorreo: string;
  nivel: "7° Año" | "8° Año" | "9° Año";
  area: string;
  saberTitulo: string;
  saberConceptual: string;
  explicacionPedagogica: string;
  indicadorCodigo: string;
  indicadorNombre: string;
  saberProcedimental: string;
  saberActitudinal: string;
  mecanica: "Simulador interactivo" | "Quiz gamificado" | "Aventura gráfica" | "Tablero de retos";
  modo: "Individual" | "Parejas";
  descripcionReto: string;
  fechaPublicacion: string;
  remixesCount: number;
  estudiantesEvaluados: number;
  tags: string[];
  codigoHTML?: string;
}

export const PRODUCCIONES_COMUNIDAD_INICIALES: WebAppComunidad[] = [
  // --------------------------------------------------------------------------
  // SÉTIMO AÑO (7°)
  // --------------------------------------------------------------------------
  {
    id: "com-7-algoritmos-sim",
    titulo: "Laboratorio de Algoritmos y Condicionales (7°)",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "7° Año",
    area: "Programación y Algoritmos",
    saberTitulo: "Lógica Proposicional, Algoritmia y Estructuras de Control",
    saberConceptual: "Algoritmo",
    explicacionPedagogica: "Un algoritmo es una secuencia finita, ordenada y no ambigua de pasos (entrada, proceso y salida) para resolver un problema de forma lógica y precisa.",
    indicadorCodigo: "7.PR.01",
    indicadorNombre: "Estructura y características esenciales del algoritmo",
    saberProcedimental: "Formula algoritmos",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Simulador interactivo",
    modo: "Individual",
    descripcionReto: "Manipula entradas de variables para observar en tiempo real cómo el algoritmo evalúa decisiones y genera resultados precisos.",
    fechaPublicacion: "2026-03-01",
    remixesCount: 42,
    estudiantesEvaluados: 310,
    tags: ["Algoritmos", "Lógica", "Secuencia", "Trabajo Cotidiano"],
  },
  {
    id: "com-7-ciberseguridad-quiz",
    titulo: "Quiz Gamificado: Ciberseguridad y Prevención de Phishing",
    autorNombre: "Profa. Elena Salazar Solís",
    autorRol: "Docente de Informática Educativa",
    autorDRE: "Heredia",
    autorCorreo: "elena.salazar.solis@mep.go.cr",
    nivel: "7° Año",
    area: "Ciencia de Datos e Inteligencia Artificial",
    saberTitulo: "Ciberseguridad, Huella Digital y Fundamentos de la IA",
    saberConceptual: "Riesgos en Línea y Ciberseguridad",
    explicacionPedagogica: "Navegar en internet requiere pensamiento crítico y cautela. El phishing suplanta sitios legítimos para robar credenciales personales.",
    indicadorCodigo: "7.CD.01",
    indicadorNombre: "Prevención de phishing, suplantación y software malicioso",
    saberProcedimental: "Maneja las tecnologías de forma ética y segura",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Quiz gamificado",
    modo: "Individual",
    descripcionReto: "Identifica correos, enlaces y mensajes sospechosos en situaciones reales para ganar la insignia de Defensor Digital.",
    fechaPublicacion: "2026-03-05",
    remixesCount: 28,
    estudiantesEvaluados: 195,
    tags: ["Ciberseguridad", "Phishing", "Seguridad Digital", "Evaluación Formativa"],
  },
  {
    id: "com-7-redes-aventura",
    titulo: "Aventura Gráfica: El Enigma del Router y la Conexión",
    autorNombre: "Prof. Carlos Méndez Rojas",
    autorRol: "Docente de Secundaria",
    autorDRE: "Cartago",
    autorCorreo: "carlos.mendez.rojas@mep.go.cr",
    nivel: "7° Año",
    area: "Apropiación Tecnológica y Digital",
    saberTitulo: "Fundamentos de Computación, Hardware, Software y Gestión de Archivos",
    saberConceptual: "Redes de Comunicación",
    explicacionPedagogica: "Una red es un conjunto de dispositivos conectados que comparten recursos e información mediante protocolos, módem y router.",
    indicadorCodigo: "7.AP.04",
    indicadorNombre: "Dispositivos de red y conectividad a Internet",
    saberProcedimental: "Reconoce patrones",
    saberActitudinal: "Aprender del error",
    mecanica: "Aventura gráfica",
    modo: "Parejas",
    descripcionReto: "Toma decisiones guiando a un paquete de datos a través de módems, routers y firewalls para llegar intacto al servidor escolar.",
    fechaPublicacion: "2026-03-10",
    remixesCount: 19,
    estudiantesEvaluados: 140,
    tags: ["Redes", "Router", "Hardware", "Conectividad"],
  },
  {
    id: "com-7-booleano-tablero",
    titulo: "Tablero de Retos: Operadores Lógicos AND, OR y NOT",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "7° Año",
    area: "Programación y Algoritmos",
    saberTitulo: "Lógica Proposicional, Algoritmia y Estructuras de Control",
    saberConceptual: "Lógica de Programación",
    explicacionPedagogica: "La lógica proposicional evalúa condiciones booleanas de verdadero o falso usando compuertas AND (conjunción), OR (disyunción) y NOT (negación).",
    indicadorCodigo: "7.PR.02",
    indicadorNombre: "Proposiciones, conectores lógicos y tablas de verdad",
    saberProcedimental: "Abstrae",
    saberActitudinal: "Aprender del error",
    mecanica: "Tablero de retos",
    modo: "Individual",
    descripcionReto: "Resuelve una matriz de retos conectando interruptores lógicos para activar las compuertas de seguridad.",
    fechaPublicacion: "2026-03-12",
    remixesCount: 35,
    estudiantesEvaluados: 260,
    tags: ["Lógica", "Booleano", "Tablas de Verdad", "Cotidiano"],
  },

  // --------------------------------------------------------------------------
  // OCTAVO AÑO (8°)
  // --------------------------------------------------------------------------
  {
    id: "com-8-circuitos-sim",
    titulo: "Simulador de Circuitos Eléctricos y Microcontroladores (8°)",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "8° Año",
    area: "Computación Física y Robótica",
    saberTitulo: "Robótica, Mecanismos, Circuitos Eléctricos y Microcontroladores",
    saberConceptual: "Circuito Eléctrico y Electrónica",
    explicacionPedagogica: "La corriente eléctrica es el flujo ordenado de electrones. El voltaje impulsa la corriente y las resistencias limitan su paso para evitar cortocircuitos.",
    indicadorCodigo: "8.ROB.02",
    indicadorNombre: "Voltaje, corriente, resistencias y conexión VCC / GND",
    saberProcedimental: "Modulariza",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Simulador interactivo",
    modo: "Individual",
    descripcionReto: "Ajusta la resistencia y el voltaje para proteger los componentes del circuito y observar la iluminación óptima del LED.",
    fechaPublicacion: "2026-02-20",
    remixesCount: 51,
    estudiantesEvaluados: 380,
    tags: ["Circuitos", "Robótica", "Voltaje", "Electrónica"],
  },
  {
    id: "com-8-listas-tablero",
    titulo: "Tablero de Retos: Estructuras de Listas y Arreglos de Datos",
    autorNombre: "Profa. Sofía Valverde Castro",
    autorRol: "Docente de Secundaria",
    autorDRE: "Alajuela",
    autorCorreo: "sofia.valverde.castro@mep.go.cr",
    nivel: "8° Año",
    area: "Ciencia de Datos e Inteligencia Artificial",
    saberTitulo: "Colecciones de Datos, Sensores, Actuadores e IA Generativa",
    saberConceptual: "Colección de Datos",
    explicacionPedagogica: "Una lista o arreglo es una estructura que almacena múltiples elementos ordenados por un índice numérico desde 0.",
    indicadorCodigo: "8.DAT.01",
    indicadorNombre: "Estructuras de listas y arreglos en programación",
    saberProcedimental: "Formula algoritmos",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Tablero de retos",
    modo: "Parejas",
    descripcionReto: "Ordena, filtra y recorre colecciones dinámicas de datos para resolver desafíos lógicos en secuencia.",
    fechaPublicacion: "2026-03-02",
    remixesCount: 22,
    estudiantesEvaluados: 165,
    tags: ["Listas", "Arreglos", "Colecciones", "Algoritmia"],
  },
  {
    id: "com-8-ia-generativa-quiz",
    titulo: "Quiz Gamificado: Prompts Éticos e Inteligencia Artificial",
    autorNombre: "Prof. Mario Alvarado Brenes",
    autorRol: "Docente de Tecnología",
    autorDRE: "San José Norte",
    autorCorreo: "mario.alvarado.brenes@mep.go.cr",
    nivel: "8° Año",
    area: "Ciencia de Datos e Inteligencia Artificial",
    saberTitulo: "Colecciones de Datos, Sensores, Actuadores e IA Generativa",
    saberConceptual: "Herramientas Generativas de IA",
    explicacionPedagogica: "Las IAs generativas crean contenidos basados en prompts. Redactar instrucciones con rol, contexto y objetivo claro mejora la calidad y evita sesgos.",
    indicadorCodigo: "8.IA.01",
    indicadorNombre: "Uso responsable de modelos generativos y prompts éticos",
    saberProcedimental: "Comunica",
    saberActitudinal: "Piensa de forma creativa",
    mecanica: "Quiz gamificado",
    modo: "Individual",
    descripcionReto: "Evalúa prompts y respuestas de IA para detectar alucinaciones y mejorar la precisión de las instrucciones.",
    fechaPublicacion: "2026-03-08",
    remixesCount: 30,
    estudiantesEvaluados: 220,
    tags: ["IA Generativa", "Prompts", "Ética Digital", "Pensamiento Crítico"],
  },
  {
    id: "com-8-rover-aventura",
    titulo: "Aventura Gráfica: La Misión del Rover Autónomo",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "8° Año",
    area: "Computación Física y Robótica",
    saberTitulo: "Robótica, Mecanismos, Circuitos Eléctricos y Microcontroladores",
    saberConceptual: "Microcontrolador",
    explicacionPedagogica: "El microcontrolador procesa datos leídos por sensores analógicos y digitales para activar motores y servomotores según las condiciones programadas.",
    indicadorCodigo: "8.ROB.03",
    indicadorNombre: "Pines digitales y analógicos de entrada/salida",
    saberProcedimental: "Programa",
    saberActitudinal: "Flexibilidad para manejar problemas",
    mecanica: "Aventura gráfica",
    modo: "Parejas",
    descripcionReto: "Guía al Rover explorador esquivando obstáculos en terreno volcánico mediante la lectura adecuada de sensores ultrasónicos.",
    fechaPublicacion: "2026-03-14",
    remixesCount: 47,
    estudiantesEvaluados: 340,
    tags: ["Microcontrolador", "Sensores", "Robótica", "Aventura"],
  },

  // --------------------------------------------------------------------------
  // NOVENO AÑO (9°)
  // --------------------------------------------------------------------------
  {
    id: "com-9-domotica-sim",
    titulo: "Simulador de Casa Domótica y Ahorro Energético (9°)",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "9° Año",
    area: "Computación Física y Robótica",
    saberTitulo: "Automatización, Domótica, Sensores y Prototipado Avanzado",
    saberConceptual: "Domótica y Automatización",
    explicacionPedagogica: "La domótica automatiza viviendas mediante sensores (temperatura, presencia, luminosidad) y actuadores para maximizar confort y eficiencia energética.",
    indicadorCodigo: "9.DOM.01",
    indicadorNombre: "Sistemas automatizados y casas inteligentes",
    saberProcedimental: "Transfiere",
    saberActitudinal: "Piensa de forma creativa",
    mecanica: "Simulador interactivo",
    modo: "Individual",
    descripcionReto: "Configura umbrales de iluminación y climatización en tiempo real para optimizar el consumo de kilowatts-hora en el hogar.",
    fechaPublicacion: "2026-02-18",
    remixesCount: 63,
    estudiantesEvaluados: 420,
    tags: ["Domótica", "Sostenibilidad", "Automatización", "Sensores"],
  },
  {
    id: "com-9-bd-tablero",
    titulo: "Tablero de Retos: Bases de Datos y Consultas de Impacto",
    autorNombre: "Profa. Karla Chaves Umaña",
    autorRol: "Docente de Informática",
    autorDRE: "Puntarenas",
    autorCorreo: "karla.chaves.umana@mep.go.cr",
    nivel: "9° Año",
    area: "Ciencia de Datos e Inteligencia Artificial",
    saberTitulo: "Bases de Datos, Ciclo de Vida del Dato y Desafíos Éticos de la IA",
    saberConceptual: "Bases de Datos y Almacenamiento",
    explicacionPedagogica: "Una base de datos almacena registros estructurados en tablas relacionadas. Las consultas permiten filtrar y resumir información estratégica.",
    indicadorCodigo: "9.BD.01",
    indicadorNombre: "Organización de datos en tablas y consultas",
    saberProcedimental: "Modulariza",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Tablero de retos",
    modo: "Individual",
    descripcionReto: "Filtra registros ambientales en tablas relacionales para identificar focos de contaminación y generar reportes analíticos.",
    fechaPublicacion: "2026-03-04",
    remixesCount: 26,
    estudiantesEvaluados: 190,
    tags: ["Bases de Datos", "Tablas", "Consultas", "Ciencia de Datos"],
  },
  {
    id: "com-9-etica-ia-aventura",
    titulo: "Aventura Gráfica: Dilemas Éticos y Sesgos en la IA",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "9° Año",
    area: "Ciencia de Datos e Inteligencia Artificial",
    saberTitulo: "Bases de Datos, Ciclo de Vida del Dato y Desafíos Éticos de la IA",
    saberConceptual: "Desafíos Éticos de la Inteligencia Artificial",
    explicacionPedagogica: "Los algoritmos de IA pueden reproducir sesgos históricos. Analizar la privacidad, la equidad algorítmica y el impacto social garantiza una tecnología justa.",
    indicadorCodigo: "9.IA.02",
    indicadorNombre: "Sesgos algorítmicos, privacidad y futuro laboral",
    saberProcedimental: "Comunica",
    saberActitudinal: "Piensa de forma creativa",
    mecanica: "Aventura gráfica",
    modo: "Parejas",
    descripcionReto: "Asume el rol de auditor ético evaluando algoritmos de contratación y diagnóstico para garantizar equidad y cero discriminación.",
    fechaPublicacion: "2026-03-11",
    remixesCount: 39,
    estudiantesEvaluados: 295,
    tags: ["Ética IA", "Sesgos", "Privacidad", "Impacto Social"],
  },
  {
    id: "com-9-sensores-quiz",
    titulo: "Quiz Gamificado: Calibración y Toma de Decisiones Autónomas",
    autorNombre: "Prof. Daniel Fonseca Porras",
    autorRol: "Docente de Robótica",
    autorDRE: "Guápiles",
    autorCorreo: "daniel.fonseca.porras@mep.go.cr",
    nivel: "9° Año",
    area: "Computación Física y Robótica",
    saberTitulo: "Automatización, Domótica, Sensores y Prototipado Avanzado",
    saberConceptual: "Integración de Sensores y Actuadores",
    explicacionPedagogica: "Calibrar sensores analógicos permite establecer rangos precisos para que el microcontrolador ejecute acciones automáticas sin error.",
    indicadorCodigo: "9.SEN.01",
    indicadorNombre: "Toma de decisiones basada en datos de sensores",
    saberProcedimental: "Modulariza",
    saberActitudinal: "Tolerancia a la frustración",
    mecanica: "Quiz gamificado",
    modo: "Individual",
    descripcionReto: "Diagnostica lecturas de sensores y ajusta parámetros de control en sistemas automatizados de alta precisión.",
    fechaPublicacion: "2026-03-15",
    remixesCount: 24,
    estudiantesEvaluados: 175,
    tags: ["Sensores", "Actuadores", "Robótica", "Calibración"],
  },
  {
    id: "com-9-diag-aula-inteligente",
    titulo: "Diagnóstico Integrado 9°: «Aula Inteligente» (Estudiante)",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "9° Año",
    area: "Computación Física y Robótica",
    saberTitulo: "Diagnóstico Integrado (Áreas Cognoscitiva, Psicomotora y Socioafectiva)",
    saberConceptual: "Microcontroladores, Sensores y Automatización",
    explicacionPedagogica: "Instrumento formativo oficial de entrada para 9° año. Evalúa conocimientos previos, reto práctico de conexionado de terminales y autorreflexión del estudiante.",
    indicadorCodigo: "9.DIAG.01",
    indicadorNombre: "Diagnóstico de entrada en Computación Física y Robótica (Módulo 1)",
    saberProcedimental: "Formula algoritmos",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Simulador interactivo",
    modo: "Individual",
    descripcionReto: "Resuelve los 10 reactivos teóricos, conecta el prototipo de hardware en 2D con osciloscopio en vivo y completa la reflexión individual de la Parte C.",
    fechaPublicacion: "2026-03-21",
    remixesCount: 88,
    estudiantesEvaluados: 560,
    tags: ["Diagnóstico 9°", "Aula Inteligente", "MEP 2026", "Evaluación Formativa", "Simulador 2D"],
  },
  {
    id: "com-9-diag-docente-evaluador",
    titulo: "Evaluador Diagnóstico Docente 9° (Nómina y Rúbrica MEP)",
    autorNombre: "Alberto Bustos Ortega",
    autorRol: "Docente de Innovación y Tecnología",
    autorDRE: "San José Central",
    autorCorreo: "alberto.bustos.ortega@mep.go.cr",
    nivel: "9° Año",
    area: "Computación Física y Robótica",
    saberTitulo: "Instrumento Oficial Docente de Evaluación Diagnóstica",
    saberConceptual: "Rúbricas de Cotejo y Observación (3 Áreas)",
    explicacionPedagogica: "Aplicativo para el docente con carga previa de nómina por archivo adjunto, evaluación individual (escala A/B/C) y consolidado grupal exportable a Excel/PDF.",
    indicadorCodigo: "9.DOC.01",
    indicadorNombre: "Sistematización y toma de decisiones pedagógicas",
    saberProcedimental: "Comunica",
    saberActitudinal: "Gusto por la precisión",
    mecanica: "Tablero de retos",
    modo: "Individual",
    descripcionReto: "Carga la lista de estudiantes de tu sección, evalúa las 10 evidencias cognoscitivas, 6 psicomotoras y 7 socioafectivas, y genera el acta oficial.",
    fechaPublicacion: "2026-03-21",
    remixesCount: 75,
    estudiantesEvaluados: 490,
    tags: ["Evaluador Docente", "Rúbrica MEP", "Diagnóstico 9°", "Excel", "Consolidado Grupal"],
  },
];

// Función para inicializar y generar el HTML completo si no viene pre-renderizado
export function obtenerProduccionConHTML(prod: WebAppComunidad): WebAppComunidad {
  if (prod.codigoHTML && prod.codigoHTML.length > 500) {
    return prod;
  }
  const opts: OpcionesGeneracionWebApp = {
    titulo: prod.titulo,
    docenteId: prod.autorCorreo.includes("alberto") ? "DOC-DRE01-7729" : "DOC-COMUNIDAD-2026",
    docenteNombre: prod.autorNombre,
    asignatura: prod.area,
    nivel: prod.nivel,
    saberTitulo: prod.saberTitulo,
    saberConceptual: prod.saberConceptual,
    explicacionPedagogica: prod.explicacionPedagogica,
    indicadorCodigo: prod.indicadorCodigo,
    indicadorNombre: prod.indicadorNombre,
    saberProcedimental: prod.saberProcedimental,
    saberActitudinal: prod.saberActitudinal,
    mecanica: prod.mecanica,
    modo: prod.modo,
    descripcionReto: prod.descripcionReto,
  };
  const html = generarCodigoHTMLAutonomo(opts);
  return { ...prod, codigoHTML: html };
}
